// ─────────────────────────────────────────────────────────────────────────────
// @njord/tokens — the single source of truth for the NJORD design system.
//
//   import { palette, severity } from '@njord/tokens'   // values, typed
//   @import "@njord/tokens/css";                        // Tailwind v4 @theme
//   @njord/tokens/njord.css                             // Ignition Perspective
//
// dist/ is generated by `npm run build`. Edit src/, never dist/.
// ─────────────────────────────────────────────────────────────────────────────

export {
  palette,
  status,
  severity,
  fluids,
  scada,
  alarmRowInk,
  severityChip,
  surface,
  text,
  border,
  tailwindColors,
} from './color.js'

export {
  fontFamilies,
  typeScale,
  mobileTypeScale,
  fontWeights,
  tailwindFontSize,
  textSizes,
} from './typography.js'
export type { TypeToken } from './typography.js'

export { radii, elevation, shell, target } from './layout.js'

export { spacing, layoutSpacing, clearance } from './spacing.js'

export { durations, easings, keyframes } from './motion.js'

export { iconSizes, iconStroke, iconSet, iconGroups, iconNames } from './icons.js'
export type { IconGroup } from './icons.js'
export type { KeyframeName } from './motion.js'

export { aliasNames, skins, skinList } from './themes.js'
export type { AliasName, Skin, SkinName } from './themes.js'

export {
  tokenGroups,
  allTokens,
  webToIgnition,
  webFontVars,
  assertTokenIntegrity,
} from './css.js'
export type { CssToken, CssGroup } from './css.js'
